const fs = require('fs-extra')
fs.mkdirpSync('NewFolder')
fs.createFileSync('./NewFolder/NewFile.txt')
fs.mkdirpSync('NewFolder2')
fs.moveSync('./NewFolder/NewFile.txt', './NewFolder2/NewFile.txt')
fs.mkdirpSync('NewFolder3')
fs.copySync('./NewFolder2/NewFile.txt', './NewFolder3/NewFile.txt')
fs.removeSync('./NewFolder2/NewFile.txt')
fs.removeSync('./NewFolder3/NewFile.txt')
fs.removeSync('./NewFolder')
fs.removeSync('./NewFolder2')
fs.removeSync('./NewFolder3')
